### PR TITLE
Faster checkouts with depth=1

### PR DESCRIPTION
**Pull request by nbuchwitz**
Use --depth 1 in git checkout in order to not checkout history. This will speedup the checkout process for users who "just" want to build a kernel with a custom config (eg. missing module).

### CODE REVIEW

**Comment by l1k** [comment]
The one issue I see here is that we want to encourage users to contribute. And you can't really contribute without a proper, fully-fledged git repo that lets you dig in the history. To alleviate that concern, how about amending the README with a hint that `--depth 1` shall be omitted if the full git history is desired, e.g. if the intention is to contribute to the project.

For piControl and kernelbakery, the difference between a full checkout and depth 1 is probably negligible, so this is only really needed for the kernel repo.

**Comment by iluminat23** [comment]
If someone wants to work with the kernel kernel source and is not able to figure that the --depth=1 will break the git history, then the person will also not be able to work with the kernel as well.

**Comment by l1k** [comment]
Somehow I knew this cowboy answer was coming... nice shooting Tex!

**Comment by nbuchwitz** [comment]
@l1k I can see your point and will add a short note regarding `--depth 1` and it's "impact".

**Comment by nbuchwitz** [comment]
@l1k @iluminat23 I added a note and also moved the README to a markdown file in order to make it consistent with our other repositories. Also I added a note about our community forum for troubleshooting.

**Review by l1k — CHANGES_REQUESTED** [review]
In the "Build 64-bit kernel (v8)" section, shouldn't the architecture given to `dpkg-buildpackage` be `aarch64`?

In line 57, you're explaining that the 32-bit kernel runs on all RevPi devices, but there's no explanation on which devices the 64-bit kernel will run (i.e. CM3/CM3+/CM4S/CM4).

Nit: In line 57, s/can be build/can be built/.

In line 47, s/make the checkout faster/make fetching faster/.

Nit: The newly added lines 21, 31, 47 and 57 lack line breaks at the 80 char limit, unlike all the other existing lines.

Nit: The README originally separated sentences with two spaces because that's what I habitually use in commit messages. (Some kernel maintainers such as <a href="https://lore.kernel.org/all/20160426214510.GA6789@localhost/">Bjorn Helgaas</a> and Rafael Wysocki use that style and may even reformat commit messages to fit, so I adopted it.) All sentences that have subsequently been added are separated with just a single space. Please choose either one and use it consistently in the newly created file.

**Comment by nbuchwitz** [comment]
@l1k I pushed an updated version where hopefully address everything you reviewed.

**Review by iluminat23 — DISMISSED** [review]

**Comment by nbuchwitz** [comment]
@iluminat23 I missed the `ARCH=arm64` in https://github.com/RevolutionPi/kernelbakery/pull/40/commits/dbad5e2100d06afeb525ae05eec23b645a652460#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R80 and had to force-push. Re-approve would be appreciated :+1:

**Review by iluminat23 — DISMISSED** [review]

**Review by l1k — COMMENTED** [review]
Is the `>` at the beginning of line 49 intentional?

Nit: Comma missing on line 50 after `history`.

**Comment by nbuchwitz** [comment]
> Is the `>` at the beginning of line 49 intentional?

Yes, this is markdown syntax which renders the note box: https://github.com/RevolutionPi/kernelbakery/pull/40/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

> Nit: Comma missing on line 50 after `history`.

fixed

**Review by l1k — APPROVED** [review]
Thanks a lot for the explanation.

**Pull request merged**
