### PR TITLE
Create Kernel release for Connect 4 (Buster) [REVPI-3230]

### PR DESCRIPTION
**Pull request by iluminat23**

### CODE REVIEW

**Comment by nbuchwitz** [comment]
Why do we need a buster package of the Connect 4 kernel?

**Comment by iluminat23** [comment]
Not for connect 4, but we want to keep the kernel packages (at least for 5.10) in sync

**Comment by l1k** [comment]
What's the plan then for releasing (or not releasing) this tag to the public via the buster dpkg repo?

The tag contains an important fix (commit RevolutionPi/piControl@1985f74eba9ebedaa310170945bc0c2e712ad7a7) but also experimental material (all the Connect 4 stuff).

Maybe release to the public with a delay of, say, 1 month, after it has been ascertained the Connect 4 changes don't introduce breakage for the older products?

**Review by l1k — APPROVED** [review]

**Comment by iluminat23** [comment]
It is planned to publish these changes to Buster after we are confident enough, that there are no regressions. This way we don't need to support different kernel versions on Buster and Bullseye.

**Pull request merged**
