### PR TITLE
Fix regular expression in grep and follow possible symlink on `/bin/true`

### PR DESCRIPTION
**Pull request by tboehler1**

### CODE REVIEW

**Review by iluminat23 — APPROVED** [review]

**Comment by l1k** [comment]
@tboehler1 Have you tested whether these changes break building a kernel on an older Debian version (say, buster)?

**Comment by tboehler1** [comment]
@l1k I have not, no. I could test this on monday morning, though.

**Comment by tboehler1** [comment]
@l1k This change still works on a fresh buster image (2023-01-12-revpi-buster.img) when running the changed line manually.

**Comment by l1k** [comment]
@tboehler1 Great, thanks for following up.

**Pull request merged**
