### PR TITLE
Create 1:9.20221118-5.10.152+revpi1 release

### PR DESCRIPTION
**Pull request by zhan-kunbus**
Signed-off-by: Zhi Han <z.han@kunbus.com>

### CODE REVIEW

**Comment by nbuchwitz** [comment]
I'm missing most of the arm64 stuff in the changelog (like `arm64/configs/revpi-v8: Add RevPi specific configuration`, etc.)?

**Comment by zhan-kunbus** [comment]
> I'm missing most of the arm64 stuff in the changelog (like `arm64/configs/revpi-v8: Add RevPi specific configuration`, etc.)?

good catch, actually, I just tried to get the commit log from arm/boot/dts, so I missed arm64.   If there are some commits in other folders, pls give me a hint.

**Review by nbuchwitz — CHANGES_REQUESTED** [review]
Missing commits in changelog:

-  ARM64: dts: Add Zero 2 W and CM4S

**Comment by zhan-kunbus** [comment]
> Missing commits in changelog:
> 
> * ARM64: dts: Add Zero 2 W and CM4S

good catch, it is added now.

**Review by nbuchwitz — APPROVED** [review]

**Review by iluminat23 — APPROVED** [review]

**Review by ferdrich-kunbus — APPROVED** [review]

**Pull request merged**
